-- ============================================================
-- Indexes for: EAP_TEMP_TRANSFORMUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_TRANSFORMUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_TRANSFORMUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_TRANSFORMUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_TRANSFORMUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_TRANSFORMUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_TRANSFORMUNIQUEIDENTIFIERS (created_by);

