-- ============================================================
-- Indexes for: EAP_T_REFPROCESSRUNTIMECONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSRUNTIMECONFIG_CREATED ON EAP_T_REFPROCESSRUNTIMECONFIG (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSRUNTIMECONFIG_MODIFIED ON EAP_T_REFPROCESSRUNTIMECONFIG (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSRUNTIMECONFIG_CREATED_BY ON EAP_T_REFPROCESSRUNTIMECONFIG (created_by);

