-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFACTIONS
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFACTIONS_CREATED ON EAP_T_REFPROCESSWFACTIONS (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFACTIONS_MODIFIED ON EAP_T_REFPROCESSWFACTIONS (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFACTIONS_CREATED_BY ON EAP_T_REFPROCESSWFACTIONS (created_by);

