-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFINPUTCOPY
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFINPUTCOPY_CREATED ON EAP_T_REFPROCESSWFINPUTCOPY (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFINPUTCOPY_MODIFIED ON EAP_T_REFPROCESSWFINPUTCOPY (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFINPUTCOPY_CREATED_BY ON EAP_T_REFPROCESSWFINPUTCOPY (created_by);

