-- ============================================================
-- Indexes for: EAP_T_UIPROCESSPARAMPGDETAIL
-- ============================================================

CREATE INDEX IDX_EAP_T_UIPROCESSPARAMPGDETAIL_CREATED ON EAP_T_UIPROCESSPARAMPGDETAIL (created_on);
CREATE INDEX IDX_EAP_T_UIPROCESSPARAMPGDETAIL_MODIFIED ON EAP_T_UIPROCESSPARAMPGDETAIL (modified_on);
CREATE INDEX IDX_EAP_T_UIPROCESSPARAMPGDETAIL_CREATED_BY ON EAP_T_UIPROCESSPARAMPGDETAIL (created_by);

