-- ============================================================
-- Indexes for: EAP_U_HISTORICALDATACALLBACK
-- ============================================================

CREATE INDEX IDX_EAP_U_HISTORICALDATACALLBACK_CREATED ON EAP_U_HISTORICALDATACALLBACK (created_on);
CREATE INDEX IDX_EAP_U_HISTORICALDATACALLBACK_MODIFIED ON EAP_U_HISTORICALDATACALLBACK (modified_on);
CREATE INDEX IDX_EAP_U_HISTORICALDATACALLBACK_CREATED_BY ON EAP_U_HISTORICALDATACALLBACK (created_by);

