-- ============================================================
-- Indexes for: EAP_T_UIADJENTITYFIELDMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_UIADJENTITYFIELDMAPPING_CREATED ON EAP_T_UIADJENTITYFIELDMAPPING (created_on);
CREATE INDEX IDX_EAP_T_UIADJENTITYFIELDMAPPING_MODIFIED ON EAP_T_UIADJENTITYFIELDMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_UIADJENTITYFIELDMAPPING_CREATED_BY ON EAP_T_UIADJENTITYFIELDMAPPING (created_by);

