-- ============================================================
-- Indexes for: EAP_TEMP_PROCESSESCALATIONRECIPIENTAUDIT
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_PROCESSESCALATIONRECIPIENTAUDIT_CREATED ON EAP_TEMP_PROCESSESCALATIONRECIPIENTAUDIT (created_on);
CREATE INDEX IDX_EAP_TEMP_PROCESSESCALATIONRECIPIENTAUDIT_MODIFIED ON EAP_TEMP_PROCESSESCALATIONRECIPIENTAUDIT (modified_on);
CREATE INDEX IDX_EAP_TEMP_PROCESSESCALATIONRECIPIENTAUDIT_CREATED_BY ON EAP_TEMP_PROCESSESCALATIONRECIPIENTAUDIT (created_by);

