-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFCUSTOMACTION
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFCUSTOMACTION_CREATED ON EAP_T_REFPROCESSWFCUSTOMACTION (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFCUSTOMACTION_MODIFIED ON EAP_T_REFPROCESSWFCUSTOMACTION (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFCUSTOMACTION_CREATED_BY ON EAP_T_REFPROCESSWFCUSTOMACTION (created_by);

