-- ============================================================
-- Indexes for: EAP_U_DWFINPUTPARSINGREQUEST
-- ============================================================

CREATE INDEX IDX_EAP_U_DWFINPUTPARSINGREQUEST_CREATED ON EAP_U_DWFINPUTPARSINGREQUEST (created_on);
CREATE INDEX IDX_EAP_U_DWFINPUTPARSINGREQUEST_MODIFIED ON EAP_U_DWFINPUTPARSINGREQUEST (modified_on);
CREATE INDEX IDX_EAP_U_DWFINPUTPARSINGREQUEST_CREATED_BY ON EAP_U_DWFINPUTPARSINGREQUEST (created_by);

