-- ============================================================
-- Indexes for: EAP_T_PROCESSESCALATIONRECIPIENTAUDIT
-- ============================================================

CREATE INDEX IDX_EAP_T_PROCESSESCALATIONRECIPIENTAUDIT_CREATED ON EAP_T_PROCESSESCALATIONRECIPIENTAUDIT (created_on);
CREATE INDEX IDX_EAP_T_PROCESSESCALATIONRECIPIENTAUDIT_MODIFIED ON EAP_T_PROCESSESCALATIONRECIPIENTAUDIT (modified_on);
CREATE INDEX IDX_EAP_T_PROCESSESCALATIONRECIPIENTAUDIT_CREATED_BY ON EAP_T_PROCESSESCALATIONRECIPIENTAUDIT (created_by);

