-- ============================================================
-- Indexes for: EAP_T_PROCESSREQUESTCUSTOMRTVALUE
-- ============================================================

CREATE INDEX IDX_EAP_T_PROCESSREQUESTCUSTOMRTVALUE_CREATED ON EAP_T_PROCESSREQUESTCUSTOMRTVALUE (created_on);
CREATE INDEX IDX_EAP_T_PROCESSREQUESTCUSTOMRTVALUE_MODIFIED ON EAP_T_PROCESSREQUESTCUSTOMRTVALUE (modified_on);
CREATE INDEX IDX_EAP_T_PROCESSREQUESTCUSTOMRTVALUE_CREATED_BY ON EAP_T_PROCESSREQUESTCUSTOMRTVALUE (created_by);

