-- ============================================================
-- Indexes for: EAP_T_REFPROCESSSHEETFIELDMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSSHEETFIELDMAPPING_CREATED ON EAP_T_REFPROCESSSHEETFIELDMAPPING (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSSHEETFIELDMAPPING_MODIFIED ON EAP_T_REFPROCESSSHEETFIELDMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSSHEETFIELDMAPPING_CREATED_BY ON EAP_T_REFPROCESSSHEETFIELDMAPPING (created_by);

