-- ============================================================
-- Indexes for: EAP_V_PROCESSCONTROLLERSTEPS
-- ============================================================

CREATE INDEX IDX_EAP_V_PROCESSCONTROLLERSTEPS_CREATED ON EAP_V_PROCESSCONTROLLERSTEPS (created_on);
CREATE INDEX IDX_EAP_V_PROCESSCONTROLLERSTEPS_MODIFIED ON EAP_V_PROCESSCONTROLLERSTEPS (modified_on);
CREATE INDEX IDX_EAP_V_PROCESSCONTROLLERSTEPS_CREATED_BY ON EAP_V_PROCESSCONTROLLERSTEPS (created_by);

