-- ============================================================
-- Indexes for: EAP_T_DVCUSTOMACTIONMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_DVCUSTOMACTIONMAPPING_CREATED ON EAP_T_DVCUSTOMACTIONMAPPING (created_on);
CREATE INDEX IDX_EAP_T_DVCUSTOMACTIONMAPPING_MODIFIED ON EAP_T_DVCUSTOMACTIONMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_DVCUSTOMACTIONMAPPING_CREATED_BY ON EAP_T_DVCUSTOMACTIONMAPPING (created_by);

