-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFTEMPLATEVERSIONS
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFTEMPLATEVERSIONS_CREATED ON EAP_T_REFPROCESSWFTEMPLATEVERSIONS (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFTEMPLATEVERSIONS_MODIFIED ON EAP_T_REFPROCESSWFTEMPLATEVERSIONS (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFTEMPLATEVERSIONS_CREATED_BY ON EAP_T_REFPROCESSWFTEMPLATEVERSIONS (created_by);

