-- ============================================================
-- Indexes for: EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A2
-- ============================================================

CREATE INDEX IDX_EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A2_CREATED ON EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A2 (created_on);
CREATE INDEX IDX_EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A2_MODIFIED ON EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A2 (modified_on);
CREATE INDEX IDX_EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A2_CREATED_BY ON EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A2 (created_by);

