-- ============================================================
-- Indexes for: EAP_T_GTOUTFILEFIELDMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_GTOUTFILEFIELDMAPPING_CREATED ON EAP_T_GTOUTFILEFIELDMAPPING (created_on);
CREATE INDEX IDX_EAP_T_GTOUTFILEFIELDMAPPING_MODIFIED ON EAP_T_GTOUTFILEFIELDMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_GTOUTFILEFIELDMAPPING_CREATED_BY ON EAP_T_GTOUTFILEFIELDMAPPING (created_by);

