-- ============================================================
-- Indexes for: EAP_T_REQUESTWFTRANSFORMTRANS
-- ============================================================

CREATE INDEX IDX_EAP_T_REQUESTWFTRANSFORMTRANS_CREATED ON EAP_T_REQUESTWFTRANSFORMTRANS (created_on);
CREATE INDEX IDX_EAP_T_REQUESTWFTRANSFORMTRANS_MODIFIED ON EAP_T_REQUESTWFTRANSFORMTRANS (modified_on);
CREATE INDEX IDX_EAP_T_REQUESTWFTRANSFORMTRANS_CREATED_BY ON EAP_T_REQUESTWFTRANSFORMTRANS (created_by);

