-- ============================================================
-- Indexes for: EAP_T_DWFPROCESSCONTROLLERCONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLERCONFIG_CREATED ON EAP_T_DWFPROCESSCONTROLLERCONFIG (created_on);
CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLERCONFIG_MODIFIED ON EAP_T_DWFPROCESSCONTROLLERCONFIG (modified_on);
CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLERCONFIG_CREATED_BY ON EAP_T_DWFPROCESSCONTROLLERCONFIG (created_by);

