-- ============================================================
-- Indexes for: EAP_T_OUTFILEGENERATIONTRANS
-- ============================================================

CREATE INDEX IDX_EAP_T_OUTFILEGENERATIONTRANS_CREATED ON EAP_T_OUTFILEGENERATIONTRANS (created_on);
CREATE INDEX IDX_EAP_T_OUTFILEGENERATIONTRANS_MODIFIED ON EAP_T_OUTFILEGENERATIONTRANS (modified_on);
CREATE INDEX IDX_EAP_T_OUTFILEGENERATIONTRANS_CREATED_BY ON EAP_T_OUTFILEGENERATIONTRANS (created_by);

