-- ============================================================
-- Indexes for: EAP_T_REFCALENDAREXCEPTIONWORKINGDAY
-- ============================================================

CREATE INDEX IDX_EAP_T_REFCALENDAREXCEPTIONWORKINGDAY_CREATED ON EAP_T_REFCALENDAREXCEPTIONWORKINGDAY (created_on);
CREATE INDEX IDX_EAP_T_REFCALENDAREXCEPTIONWORKINGDAY_MODIFIED ON EAP_T_REFCALENDAREXCEPTIONWORKINGDAY (modified_on);
CREATE INDEX IDX_EAP_T_REFCALENDAREXCEPTIONWORKINGDAY_CREATED_BY ON EAP_T_REFCALENDAREXCEPTIONWORKINGDAY (created_by);

