-- ============================================================
-- Indexes for: EAP_TEMP_HISTORICALDATAFREQUENCY
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_HISTORICALDATAFREQUENCY_CREATED ON EAP_TEMP_HISTORICALDATAFREQUENCY (created_on);
CREATE INDEX IDX_EAP_TEMP_HISTORICALDATAFREQUENCY_MODIFIED ON EAP_TEMP_HISTORICALDATAFREQUENCY (modified_on);
CREATE INDEX IDX_EAP_TEMP_HISTORICALDATAFREQUENCY_CREATED_BY ON EAP_TEMP_HISTORICALDATAFREQUENCY (created_by);

