-- ============================================================
-- Indexes for: EAP_TEMP_HISTORICALDATACALLPARAM
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_HISTORICALDATACALLPARAM_CREATED ON EAP_TEMP_HISTORICALDATACALLPARAM (created_on);
CREATE INDEX IDX_EAP_TEMP_HISTORICALDATACALLPARAM_MODIFIED ON EAP_TEMP_HISTORICALDATACALLPARAM (modified_on);
CREATE INDEX IDX_EAP_TEMP_HISTORICALDATACALLPARAM_CREATED_BY ON EAP_TEMP_HISTORICALDATACALLPARAM (created_by);

