-- ============================================================
-- Indexes for: EAP_T_GTOUTFILEENTITYMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_GTOUTFILEENTITYMAPPING_CREATED ON EAP_T_GTOUTFILEENTITYMAPPING (created_on);
CREATE INDEX IDX_EAP_T_GTOUTFILEENTITYMAPPING_MODIFIED ON EAP_T_GTOUTFILEENTITYMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_GTOUTFILEENTITYMAPPING_CREATED_BY ON EAP_T_GTOUTFILEENTITYMAPPING (created_by);

