-- ============================================================
-- Indexes for: EAP_TEMP_OUTPUTCONFIGUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_OUTPUTCONFIGUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_OUTPUTCONFIGUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_OUTPUTCONFIGUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_OUTPUTCONFIGUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_OUTPUTCONFIGUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_OUTPUTCONFIGUNIQUEIDENTIFIERS (created_by);

