-- ============================================================
-- Indexes for: EAP_T_LINKEUCTRANSMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_LINKEUCTRANSMAPPING_CREATED ON EAP_T_LINKEUCTRANSMAPPING (created_on);
CREATE INDEX IDX_EAP_T_LINKEUCTRANSMAPPING_MODIFIED ON EAP_T_LINKEUCTRANSMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_LINKEUCTRANSMAPPING_CREATED_BY ON EAP_T_LINKEUCTRANSMAPPING (created_by);

