-- ============================================================
-- Indexes for: EAP_T_UIPROCESSPARAMPGCONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_UIPROCESSPARAMPGCONFIG_CREATED ON EAP_T_UIPROCESSPARAMPGCONFIG (created_on);
CREATE INDEX IDX_EAP_T_UIPROCESSPARAMPGCONFIG_MODIFIED ON EAP_T_UIPROCESSPARAMPGCONFIG (modified_on);
CREATE INDEX IDX_EAP_T_UIPROCESSPARAMPGCONFIG_CREATED_BY ON EAP_T_UIPROCESSPARAMPGCONFIG (created_by);

