-- ============================================================
-- Indexes for: EAP_T_BULKUSERSUPLDRAWTRANS
-- ============================================================

CREATE INDEX IDX_EAP_T_BULKUSERSUPLDRAWTRANS_CREATED ON EAP_T_BULKUSERSUPLDRAWTRANS (created_on);
CREATE INDEX IDX_EAP_T_BULKUSERSUPLDRAWTRANS_MODIFIED ON EAP_T_BULKUSERSUPLDRAWTRANS (modified_on);
CREATE INDEX IDX_EAP_T_BULKUSERSUPLDRAWTRANS_CREATED_BY ON EAP_T_BULKUSERSUPLDRAWTRANS (created_by);

