-- ============================================================
-- Indexes for: EAP_T_DVENTITYSHEETFILTERS
-- ============================================================

CREATE INDEX IDX_EAP_T_DVENTITYSHEETFILTERS_CREATED ON EAP_T_DVENTITYSHEETFILTERS (created_on);
CREATE INDEX IDX_EAP_T_DVENTITYSHEETFILTERS_MODIFIED ON EAP_T_DVENTITYSHEETFILTERS (modified_on);
CREATE INDEX IDX_EAP_T_DVENTITYSHEETFILTERS_CREATED_BY ON EAP_T_DVENTITYSHEETFILTERS (created_by);

