-- ============================================================
-- Indexes for: EAP_TEMP_EXPORTTOEXCELSCHEDULEDVIEW
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_EXPORTTOEXCELSCHEDULEDVIEW_CREATED ON EAP_TEMP_EXPORTTOEXCELSCHEDULEDVIEW (created_on);
CREATE INDEX IDX_EAP_TEMP_EXPORTTOEXCELSCHEDULEDVIEW_MODIFIED ON EAP_TEMP_EXPORTTOEXCELSCHEDULEDVIEW (modified_on);
CREATE INDEX IDX_EAP_TEMP_EXPORTTOEXCELSCHEDULEDVIEW_CREATED_BY ON EAP_TEMP_EXPORTTOEXCELSCHEDULEDVIEW (created_by);

