-- ============================================================
-- Indexes for: EAP_T_RUNTIMESCHEDULERDETAIL
-- ============================================================

CREATE INDEX IDX_EAP_T_RUNTIMESCHEDULERDETAIL_CREATED ON EAP_T_RUNTIMESCHEDULERDETAIL (created_on);
CREATE INDEX IDX_EAP_T_RUNTIMESCHEDULERDETAIL_MODIFIED ON EAP_T_RUNTIMESCHEDULERDETAIL (modified_on);
CREATE INDEX IDX_EAP_T_RUNTIMESCHEDULERDETAIL_CREATED_BY ON EAP_T_RUNTIMESCHEDULERDETAIL (created_by);

