-- ============================================================
-- Indexes for: EAP_V_PROCESSDATAVALIDATIONTEMPLATECONFIG
-- ============================================================

CREATE INDEX IDX_EAP_V_PROCESSDATAVALIDATIONTEMPLATECONFIG_CREATED ON EAP_V_PROCESSDATAVALIDATIONTEMPLATECONFIG (created_on);
CREATE INDEX IDX_EAP_V_PROCESSDATAVALIDATIONTEMPLATECONFIG_MODIFIED ON EAP_V_PROCESSDATAVALIDATIONTEMPLATECONFIG (modified_on);
CREATE INDEX IDX_EAP_V_PROCESSDATAVALIDATIONTEMPLATECONFIG_CREATED_BY ON EAP_V_PROCESSDATAVALIDATIONTEMPLATECONFIG (created_by);

