-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFSHEETCOPY
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETCOPY_CREATED ON EAP_T_REFPROCESSWFSHEETCOPY (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETCOPY_MODIFIED ON EAP_T_REFPROCESSWFSHEETCOPY (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETCOPY_CREATED_BY ON EAP_T_REFPROCESSWFSHEETCOPY (created_by);

