-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFCUSTOMACTIONMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFCUSTOMACTIONMAPPING_CREATED ON EAP_T_REFPROCESSWFCUSTOMACTIONMAPPING (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFCUSTOMACTIONMAPPING_MODIFIED ON EAP_T_REFPROCESSWFCUSTOMACTIONMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFCUSTOMACTIONMAPPING_CREATED_BY ON EAP_T_REFPROCESSWFCUSTOMACTIONMAPPING (created_by);

