-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFFIXEDCELLS
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFFIXEDCELLS_CREATED ON EAP_T_REFPROCESSWFFIXEDCELLS (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFFIXEDCELLS_MODIFIED ON EAP_T_REFPROCESSWFFIXEDCELLS (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFFIXEDCELLS_CREATED_BY ON EAP_T_REFPROCESSWFFIXEDCELLS (created_by);

