-- ============================================================
-- Indexes for: EAP_T_REFPROCESSHISTENTITYMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSHISTENTITYMAPPING_CREATED ON EAP_T_REFPROCESSHISTENTITYMAPPING (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSHISTENTITYMAPPING_MODIFIED ON EAP_T_REFPROCESSHISTENTITYMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSHISTENTITYMAPPING_CREATED_BY ON EAP_T_REFPROCESSHISTENTITYMAPPING (created_by);

