-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFTEMPLATECONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFTEMPLATECONFIG_CREATED ON EAP_T_REFPROCESSWFTEMPLATECONFIG (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFTEMPLATECONFIG_MODIFIED ON EAP_T_REFPROCESSWFTEMPLATECONFIG (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFTEMPLATECONFIG_CREATED_BY ON EAP_T_REFPROCESSWFTEMPLATECONFIG (created_by);

