-- ============================================================
-- Indexes for: EAP_T_REFCALENDARHOLIDAY
-- ============================================================

CREATE INDEX IDX_EAP_T_REFCALENDARHOLIDAY_CREATED ON EAP_T_REFCALENDARHOLIDAY (created_on);
CREATE INDEX IDX_EAP_T_REFCALENDARHOLIDAY_MODIFIED ON EAP_T_REFCALENDARHOLIDAY (modified_on);
CREATE INDEX IDX_EAP_T_REFCALENDARHOLIDAY_CREATED_BY ON EAP_T_REFCALENDARHOLIDAY (created_by);

