-- ============================================================
-- Indexes for: EAP_TEMP_PROCESSPARAMSUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_PROCESSPARAMSUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_PROCESSPARAMSUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_PROCESSPARAMSUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_PROCESSPARAMSUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_PROCESSPARAMSUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_PROCESSPARAMSUNIQUEIDENTIFIERS (created_by);

