-- ============================================================
-- Indexes for: EAP_VIEW_PROCESS_REQUEST_AUDIT
-- ============================================================

CREATE INDEX IDX_EAP_VIEW_PROCESS_REQUEST_AUDIT_CREATED ON EAP_VIEW_PROCESS_REQUEST_AUDIT (created_on);
CREATE INDEX IDX_EAP_VIEW_PROCESS_REQUEST_AUDIT_MODIFIED ON EAP_VIEW_PROCESS_REQUEST_AUDIT (modified_on);
CREATE INDEX IDX_EAP_VIEW_PROCESS_REQUEST_AUDIT_CREATED_BY ON EAP_VIEW_PROCESS_REQUEST_AUDIT (created_by);

