-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFSHEETCOPYMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETCOPYMAPPING_CREATED ON EAP_T_REFPROCESSWFSHEETCOPYMAPPING (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETCOPYMAPPING_MODIFIED ON EAP_T_REFPROCESSWFSHEETCOPYMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETCOPYMAPPING_CREATED_BY ON EAP_T_REFPROCESSWFSHEETCOPYMAPPING (created_by);

