-- ============================================================
-- Indexes for: EAP_T_OUTEMAILATTRIBUTECONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_OUTEMAILATTRIBUTECONFIG_CREATED ON EAP_T_OUTEMAILATTRIBUTECONFIG (created_on);
CREATE INDEX IDX_EAP_T_OUTEMAILATTRIBUTECONFIG_MODIFIED ON EAP_T_OUTEMAILATTRIBUTECONFIG (modified_on);
CREATE INDEX IDX_EAP_T_OUTEMAILATTRIBUTECONFIG_CREATED_BY ON EAP_T_OUTEMAILATTRIBUTECONFIG (created_by);

