-- ============================================================
-- Indexes for: EAP_TEMP_EMAILTEMPLATEUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_EMAILTEMPLATEUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_EMAILTEMPLATEUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_EMAILTEMPLATEUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_EMAILTEMPLATEUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_EMAILTEMPLATEUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_EMAILTEMPLATEUNIQUEIDENTIFIERS (created_by);

