-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFENTITYSHEETMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFENTITYSHEETMAPPING_CREATED ON EAP_T_REFPROCESSWFENTITYSHEETMAPPING (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFENTITYSHEETMAPPING_MODIFIED ON EAP_T_REFPROCESSWFENTITYSHEETMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFENTITYSHEETMAPPING_CREATED_BY ON EAP_T_REFPROCESSWFENTITYSHEETMAPPING (created_by);

