-- ============================================================
-- Indexes for: EAP_T_REFPROCESSINFILEENTITYMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSINFILEENTITYMAPPING_CREATED ON EAP_T_REFPROCESSINFILEENTITYMAPPING (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSINFILEENTITYMAPPING_MODIFIED ON EAP_T_REFPROCESSINFILEENTITYMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSINFILEENTITYMAPPING_CREATED_BY ON EAP_T_REFPROCESSINFILEENTITYMAPPING (created_by);

