-- ============================================================
-- Indexes for: EAP_U_MANUALUPLOADATTACHMENTDATA
-- ============================================================

CREATE INDEX IDX_EAP_U_MANUALUPLOADATTACHMENTDATA_CREATED ON EAP_U_MANUALUPLOADATTACHMENTDATA (created_on);
CREATE INDEX IDX_EAP_U_MANUALUPLOADATTACHMENTDATA_MODIFIED ON EAP_U_MANUALUPLOADATTACHMENTDATA (modified_on);
CREATE INDEX IDX_EAP_U_MANUALUPLOADATTACHMENTDATA_CREATED_BY ON EAP_U_MANUALUPLOADATTACHMENTDATA (created_by);

