-- ============================================================
-- Indexes for: EAP_T_REFPROCESSSHEETTRANSPOSECONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSSHEETTRANSPOSECONFIG_CREATED ON EAP_T_REFPROCESSSHEETTRANSPOSECONFIG (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSSHEETTRANSPOSECONFIG_MODIFIED ON EAP_T_REFPROCESSSHEETTRANSPOSECONFIG (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSSHEETTRANSPOSECONFIG_CREATED_BY ON EAP_T_REFPROCESSSHEETTRANSPOSECONFIG (created_by);

