-- ============================================================
-- Indexes for: EAP_V_PROCESSTEMPLATECONFIG
-- ============================================================

CREATE INDEX IDX_EAP_V_PROCESSTEMPLATECONFIG_CREATED ON EAP_V_PROCESSTEMPLATECONFIG (created_on);
CREATE INDEX IDX_EAP_V_PROCESSTEMPLATECONFIG_MODIFIED ON EAP_V_PROCESSTEMPLATECONFIG (modified_on);
CREATE INDEX IDX_EAP_V_PROCESSTEMPLATECONFIG_CREATED_BY ON EAP_V_PROCESSTEMPLATECONFIG (created_by);

