-- ============================================================
-- Indexes for: EAP_T_REFCOUNTRYNONWORKINGDAY
-- ============================================================

CREATE INDEX IDX_EAP_T_REFCOUNTRYNONWORKINGDAY_CREATED ON EAP_T_REFCOUNTRYNONWORKINGDAY (created_on);
CREATE INDEX IDX_EAP_T_REFCOUNTRYNONWORKINGDAY_MODIFIED ON EAP_T_REFCOUNTRYNONWORKINGDAY (modified_on);
CREATE INDEX IDX_EAP_T_REFCOUNTRYNONWORKINGDAY_CREATED_BY ON EAP_T_REFCOUNTRYNONWORKINGDAY (created_by);

