-- ============================================================
-- Indexes for: EAP_T_PROCESSESCALATIONRECIPIENT
-- ============================================================

CREATE INDEX IDX_EAP_T_PROCESSESCALATIONRECIPIENT_CREATED ON EAP_T_PROCESSESCALATIONRECIPIENT (created_on);
CREATE INDEX IDX_EAP_T_PROCESSESCALATIONRECIPIENT_MODIFIED ON EAP_T_PROCESSESCALATIONRECIPIENT (modified_on);
CREATE INDEX IDX_EAP_T_PROCESSESCALATIONRECIPIENT_CREATED_BY ON EAP_T_PROCESSESCALATIONRECIPIENT (created_by);

