-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFREFRESHPIVOT
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFREFRESHPIVOT_CREATED ON EAP_T_REFPROCESSWFREFRESHPIVOT (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFREFRESHPIVOT_MODIFIED ON EAP_T_REFPROCESSWFREFRESHPIVOT (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFREFRESHPIVOT_CREATED_BY ON EAP_T_REFPROCESSWFREFRESHPIVOT (created_by);

