-- ============================================================
-- Indexes for: EAP_T_REFPROCESSOUTFILETYPE
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSOUTFILETYPE_CREATED ON EAP_T_REFPROCESSOUTFILETYPE (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSOUTFILETYPE_MODIFIED ON EAP_T_REFPROCESSOUTFILETYPE (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSOUTFILETYPE_CREATED_BY ON EAP_T_REFPROCESSOUTFILETYPE (created_by);

