-- ============================================================
-- Indexes for: EAP_TEMP_STATUSMILESTONEANDTRACIBILITYREPORT
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_STATUSMILESTONEANDTRACIBILITYREPORT_CREATED ON EAP_TEMP_STATUSMILESTONEANDTRACIBILITYREPORT (created_on);
CREATE INDEX IDX_EAP_TEMP_STATUSMILESTONEANDTRACIBILITYREPORT_MODIFIED ON EAP_TEMP_STATUSMILESTONEANDTRACIBILITYREPORT (modified_on);
CREATE INDEX IDX_EAP_TEMP_STATUSMILESTONEANDTRACIBILITYREPORT_CREATED_BY ON EAP_TEMP_STATUSMILESTONEANDTRACIBILITYREPORT (created_by);

