-- ============================================================
-- Indexes for: EAP_T_REFCALENDARNONWORKINGDAY
-- ============================================================

CREATE INDEX IDX_EAP_T_REFCALENDARNONWORKINGDAY_CREATED ON EAP_T_REFCALENDARNONWORKINGDAY (created_on);
CREATE INDEX IDX_EAP_T_REFCALENDARNONWORKINGDAY_MODIFIED ON EAP_T_REFCALENDARNONWORKINGDAY (modified_on);
CREATE INDEX IDX_EAP_T_REFCALENDARNONWORKINGDAY_CREATED_BY ON EAP_T_REFCALENDARNONWORKINGDAY (created_by);

