-- ============================================================
-- Indexes for: EAP_T_REFCALENDARCOUNTRYDETAILS
-- ============================================================

CREATE INDEX IDX_EAP_T_REFCALENDARCOUNTRYDETAILS_CREATED ON EAP_T_REFCALENDARCOUNTRYDETAILS (created_on);
CREATE INDEX IDX_EAP_T_REFCALENDARCOUNTRYDETAILS_MODIFIED ON EAP_T_REFCALENDARCOUNTRYDETAILS (modified_on);
CREATE INDEX IDX_EAP_T_REFCALENDARCOUNTRYDETAILS_CREATED_BY ON EAP_T_REFCALENDARCOUNTRYDETAILS (created_by);

