-- ============================================================
-- Indexes for: EAP_T_UIOUTENTITYFIELDMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_UIOUTENTITYFIELDMAPPING_CREATED ON EAP_T_UIOUTENTITYFIELDMAPPING (created_on);
CREATE INDEX IDX_EAP_T_UIOUTENTITYFIELDMAPPING_MODIFIED ON EAP_T_UIOUTENTITYFIELDMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_UIOUTENTITYFIELDMAPPING_CREATED_BY ON EAP_T_UIOUTENTITYFIELDMAPPING (created_by);

