-- ============================================================
-- Indexes for: EAP_T_REFPROCESSSHEETFIXEDCELLSCONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSSHEETFIXEDCELLSCONFIG_CREATED ON EAP_T_REFPROCESSSHEETFIXEDCELLSCONFIG (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSSHEETFIXEDCELLSCONFIG_MODIFIED ON EAP_T_REFPROCESSSHEETFIXEDCELLSCONFIG (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSSHEETFIXEDCELLSCONFIG_CREATED_BY ON EAP_T_REFPROCESSSHEETFIXEDCELLSCONFIG (created_by);

