-- ============================================================
-- Indexes for: EAP_T_DVTRANSPOSEMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_DVTRANSPOSEMAPPING_CREATED ON EAP_T_DVTRANSPOSEMAPPING (created_on);
CREATE INDEX IDX_EAP_T_DVTRANSPOSEMAPPING_MODIFIED ON EAP_T_DVTRANSPOSEMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_DVTRANSPOSEMAPPING_CREATED_BY ON EAP_T_DVTRANSPOSEMAPPING (created_by);

