-- ============================================================
-- Indexes for: EAP_T_PROCESSINFILEPARSINGTRANS
-- ============================================================

CREATE INDEX IDX_EAP_T_PROCESSINFILEPARSINGTRANS_CREATED ON EAP_T_PROCESSINFILEPARSINGTRANS (created_on);
CREATE INDEX IDX_EAP_T_PROCESSINFILEPARSINGTRANS_MODIFIED ON EAP_T_PROCESSINFILEPARSINGTRANS (modified_on);
CREATE INDEX IDX_EAP_T_PROCESSINFILEPARSINGTRANS_CREATED_BY ON EAP_T_PROCESSINFILEPARSINGTRANS (created_by);

