-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFCALLBACKPROCESSMODELS
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFCALLBACKPROCESSMODELS_CREATED ON EAP_T_REFPROCESSWFCALLBACKPROCESSMODELS (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFCALLBACKPROCESSMODELS_MODIFIED ON EAP_T_REFPROCESSWFCALLBACKPROCESSMODELS (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFCALLBACKPROCESSMODELS_CREATED_BY ON EAP_T_REFPROCESSWFCALLBACKPROCESSMODELS (created_by);

