-- ============================================================
-- Indexes for: EAP_TEMP_DATAVALIDATIONUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_DATAVALIDATIONUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_DATAVALIDATIONUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_DATAVALIDATIONUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_DATAVALIDATIONUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_DATAVALIDATIONUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_DATAVALIDATIONUNIQUEIDENTIFIERS (created_by);

