-- ============================================================
-- Indexes for: EAP_V_PROCESSCONTROLLERCONFIG
-- ============================================================

CREATE INDEX IDX_EAP_V_PROCESSCONTROLLERCONFIG_CREATED ON EAP_V_PROCESSCONTROLLERCONFIG (created_on);
CREATE INDEX IDX_EAP_V_PROCESSCONTROLLERCONFIG_MODIFIED ON EAP_V_PROCESSCONTROLLERCONFIG (modified_on);
CREATE INDEX IDX_EAP_V_PROCESSCONTROLLERCONFIG_CREATED_BY ON EAP_V_PROCESSCONTROLLERCONFIG (created_by);

