-- ============================================================
-- Indexes for: EAP_T_PROCESSCUSTOMRTCONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_PROCESSCUSTOMRTCONFIG_CREATED ON EAP_T_PROCESSCUSTOMRTCONFIG (created_on);
CREATE INDEX IDX_EAP_T_PROCESSCUSTOMRTCONFIG_MODIFIED ON EAP_T_PROCESSCUSTOMRTCONFIG (modified_on);
CREATE INDEX IDX_EAP_T_PROCESSCUSTOMRTCONFIG_CREATED_BY ON EAP_T_PROCESSCUSTOMRTCONFIG (created_by);

