-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFSHEETENTITYMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETENTITYMAPPING_CREATED ON EAP_T_REFPROCESSWFSHEETENTITYMAPPING (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETENTITYMAPPING_MODIFIED ON EAP_T_REFPROCESSWFSHEETENTITYMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETENTITYMAPPING_CREATED_BY ON EAP_T_REFPROCESSWFSHEETENTITYMAPPING (created_by);

