-- ============================================================
-- Indexes for: EAP_T_OUTEMAILPROCESSTEMPLATEMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_OUTEMAILPROCESSTEMPLATEMAPPING_CREATED ON EAP_T_OUTEMAILPROCESSTEMPLATEMAPPING (created_on);
CREATE INDEX IDX_EAP_T_OUTEMAILPROCESSTEMPLATEMAPPING_MODIFIED ON EAP_T_OUTEMAILPROCESSTEMPLATEMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_OUTEMAILPROCESSTEMPLATEMAPPING_CREATED_BY ON EAP_T_OUTEMAILPROCESSTEMPLATEMAPPING (created_by);

