-- ============================================================
-- Indexes for: EAP_T_PROCESSREQUESTAUDIT
-- ============================================================

CREATE INDEX IDX_EAP_T_PROCESSREQUESTAUDIT_CREATED ON EAP_T_PROCESSREQUESTAUDIT (created_on);
CREATE INDEX IDX_EAP_T_PROCESSREQUESTAUDIT_MODIFIED ON EAP_T_PROCESSREQUESTAUDIT (modified_on);
CREATE INDEX IDX_EAP_T_PROCESSREQUESTAUDIT_CREATED_BY ON EAP_T_PROCESSREQUESTAUDIT (created_by);

