-- ============================================================
-- Indexes for: EAP_T_GTSHEETFIXEDCELLSCONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_GTSHEETFIXEDCELLSCONFIG_CREATED ON EAP_T_GTSHEETFIXEDCELLSCONFIG (created_on);
CREATE INDEX IDX_EAP_T_GTSHEETFIXEDCELLSCONFIG_MODIFIED ON EAP_T_GTSHEETFIXEDCELLSCONFIG (modified_on);
CREATE INDEX IDX_EAP_T_GTSHEETFIXEDCELLSCONFIG_CREATED_BY ON EAP_T_GTSHEETFIXEDCELLSCONFIG (created_by);

