-- ============================================================
-- Indexes for: EAP_TEMP_HISTORICALDATAUPLOAD
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_HISTORICALDATAUPLOAD_CREATED ON EAP_TEMP_HISTORICALDATAUPLOAD (created_on);
CREATE INDEX IDX_EAP_TEMP_HISTORICALDATAUPLOAD_MODIFIED ON EAP_TEMP_HISTORICALDATAUPLOAD (modified_on);
CREATE INDEX IDX_EAP_TEMP_HISTORICALDATAUPLOAD_CREATED_BY ON EAP_TEMP_HISTORICALDATAUPLOAD (created_by);

