-- ============================================================
-- Indexes for: EAP_TEMP_UIVIEWCONFIGUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_UIVIEWCONFIGUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_UIVIEWCONFIGUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_UIVIEWCONFIGUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_UIVIEWCONFIGUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_UIVIEWCONFIGUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_UIVIEWCONFIGUNIQUEIDENTIFIERS (created_by);

