-- ============================================================
-- Indexes for: EAP_T_UIINENTITYFIELDMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_UIINENTITYFIELDMAPPING_CREATED ON EAP_T_UIINENTITYFIELDMAPPING (created_on);
CREATE INDEX IDX_EAP_T_UIINENTITYFIELDMAPPING_MODIFIED ON EAP_T_UIINENTITYFIELDMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_UIINENTITYFIELDMAPPING_CREATED_BY ON EAP_T_UIINENTITYFIELDMAPPING (created_by);

