-- ============================================================
-- Indexes for: EAP_T_DWFPROCESSCONTROLLERMASTER
-- ============================================================

CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLERMASTER_CREATED ON EAP_T_DWFPROCESSCONTROLLERMASTER (created_on);
CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLERMASTER_MODIFIED ON EAP_T_DWFPROCESSCONTROLLERMASTER (modified_on);
CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLERMASTER_CREATED_BY ON EAP_T_DWFPROCESSCONTROLLERMASTER (created_by);

