-- ============================================================
-- Indexes for: EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A1
-- ============================================================

CREATE INDEX IDX_EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A1_CREATED ON EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A1 (created_on);
CREATE INDEX IDX_EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A1_MODIFIED ON EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A1 (modified_on);
CREATE INDEX IDX_EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A1_CREATED_BY ON EAP_DYNAMIC_ALL_INVESTORS_SCHEDULE_A1 (created_by);

