-- ============================================================
-- Indexes for: EAP_T_OUTEMAILATTRIBUTEMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_OUTEMAILATTRIBUTEMAPPING_CREATED ON EAP_T_OUTEMAILATTRIBUTEMAPPING (created_on);
CREATE INDEX IDX_EAP_T_OUTEMAILATTRIBUTEMAPPING_MODIFIED ON EAP_T_OUTEMAILATTRIBUTEMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_OUTEMAILATTRIBUTEMAPPING_CREATED_BY ON EAP_T_OUTEMAILATTRIBUTEMAPPING (created_by);

