-- ============================================================
-- Indexes for: EAP_T_REFPROCESSHISTDETAILTRANS
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSHISTDETAILTRANS_CREATED ON EAP_T_REFPROCESSHISTDETAILTRANS (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSHISTDETAILTRANS_MODIFIED ON EAP_T_REFPROCESSHISTDETAILTRANS (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSHISTDETAILTRANS_CREATED_BY ON EAP_T_REFPROCESSHISTDETAILTRANS (created_by);

