-- ============================================================
-- Indexes for: EAP_V_RUNTIMESCHEDULERDETAIL
-- ============================================================

CREATE INDEX IDX_EAP_V_RUNTIMESCHEDULERDETAIL_CREATED ON EAP_V_RUNTIMESCHEDULERDETAIL (created_on);
CREATE INDEX IDX_EAP_V_RUNTIMESCHEDULERDETAIL_MODIFIED ON EAP_V_RUNTIMESCHEDULERDETAIL (modified_on);
CREATE INDEX IDX_EAP_V_RUNTIMESCHEDULERDETAIL_CREATED_BY ON EAP_V_RUNTIMESCHEDULERDETAIL (created_by);

