-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFOUTPUTCOPY
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFOUTPUTCOPY_CREATED ON EAP_T_REFPROCESSWFOUTPUTCOPY (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFOUTPUTCOPY_MODIFIED ON EAP_T_REFPROCESSWFOUTPUTCOPY (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFOUTPUTCOPY_CREATED_BY ON EAP_T_REFPROCESSWFOUTPUTCOPY (created_by);

