-- ============================================================
-- Indexes for: EAP_U_SOURCEINTEGRATIONCALLBACK
-- ============================================================

CREATE INDEX IDX_EAP_U_SOURCEINTEGRATIONCALLBACK_CREATED ON EAP_U_SOURCEINTEGRATIONCALLBACK (created_on);
CREATE INDEX IDX_EAP_U_SOURCEINTEGRATIONCALLBACK_MODIFIED ON EAP_U_SOURCEINTEGRATIONCALLBACK (modified_on);
CREATE INDEX IDX_EAP_U_SOURCEINTEGRATIONCALLBACK_CREATED_BY ON EAP_U_SOURCEINTEGRATIONCALLBACK (created_by);

