-- ============================================================
-- Indexes for: EAP_T_REFPROCESSWFSHEETFILTERS
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETFILTERS_CREATED ON EAP_T_REFPROCESSWFSHEETFILTERS (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETFILTERS_MODIFIED ON EAP_T_REFPROCESSWFSHEETFILTERS (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSWFSHEETFILTERS_CREATED_BY ON EAP_T_REFPROCESSWFSHEETFILTERS (created_by);

