-- ============================================================
-- Indexes for: EAP_T_DVCALLBACKPROCESSMODELS
-- ============================================================

CREATE INDEX IDX_EAP_T_DVCALLBACKPROCESSMODELS_CREATED ON EAP_T_DVCALLBACKPROCESSMODELS (created_on);
CREATE INDEX IDX_EAP_T_DVCALLBACKPROCESSMODELS_MODIFIED ON EAP_T_DVCALLBACKPROCESSMODELS (modified_on);
CREATE INDEX IDX_EAP_T_DVCALLBACKPROCESSMODELS_CREATED_BY ON EAP_T_DVCALLBACKPROCESSMODELS (created_by);

