-- ============================================================
-- Indexes for: EAP_T_PROCESSMILESTONESTEPTRANS
-- ============================================================

CREATE INDEX IDX_EAP_T_PROCESSMILESTONESTEPTRANS_CREATED ON EAP_T_PROCESSMILESTONESTEPTRANS (created_on);
CREATE INDEX IDX_EAP_T_PROCESSMILESTONESTEPTRANS_MODIFIED ON EAP_T_PROCESSMILESTONESTEPTRANS (modified_on);
CREATE INDEX IDX_EAP_T_PROCESSMILESTONESTEPTRANS_CREATED_BY ON EAP_T_PROCESSMILESTONESTEPTRANS (created_by);

