-- ============================================================
-- Indexes for: EAP_TEMP_PARSINGUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_PARSINGUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_PARSINGUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_PARSINGUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_PARSINGUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_PARSINGUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_PARSINGUNIQUEIDENTIFIERS (created_by);

