-- ============================================================
-- Indexes for: EAP_TEMP_DWFUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_DWFUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_DWFUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_DWFUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_DWFUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_DWFUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_DWFUNIQUEIDENTIFIERS (created_by);

