-- ============================================================
-- Indexes for: EAP_T_DWFPROCESSCONTROLLER
-- ============================================================

CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLER_CREATED ON EAP_T_DWFPROCESSCONTROLLER (created_on);
CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLER_MODIFIED ON EAP_T_DWFPROCESSCONTROLLER (modified_on);
CREATE INDEX IDX_EAP_T_DWFPROCESSCONTROLLER_CREATED_BY ON EAP_T_DWFPROCESSCONTROLLER (created_by);

