-- ============================================================
-- Indexes for: EAP_TEMP_PROCESSPARAMVALUES
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_PROCESSPARAMVALUES_CREATED ON EAP_TEMP_PROCESSPARAMVALUES (created_on);
CREATE INDEX IDX_EAP_TEMP_PROCESSPARAMVALUES_MODIFIED ON EAP_TEMP_PROCESSPARAMVALUES (modified_on);
CREATE INDEX IDX_EAP_TEMP_PROCESSPARAMVALUES_CREATED_BY ON EAP_TEMP_PROCESSPARAMVALUES (created_by);

