-- ============================================================
-- Indexes for: EAP_T_UIADJENTITYMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_UIADJENTITYMAPPING_CREATED ON EAP_T_UIADJENTITYMAPPING (created_on);
CREATE INDEX IDX_EAP_T_UIADJENTITYMAPPING_MODIFIED ON EAP_T_UIADJENTITYMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_UIADJENTITYMAPPING_CREATED_BY ON EAP_T_UIADJENTITYMAPPING (created_by);

