-- ============================================================
-- Indexes for: EAP_T_REFPROCESSHISTSHEETFIELDMAPPING
-- ============================================================

CREATE INDEX IDX_EAP_T_REFPROCESSHISTSHEETFIELDMAPPING_CREATED ON EAP_T_REFPROCESSHISTSHEETFIELDMAPPING (created_on);
CREATE INDEX IDX_EAP_T_REFPROCESSHISTSHEETFIELDMAPPING_MODIFIED ON EAP_T_REFPROCESSHISTSHEETFIELDMAPPING (modified_on);
CREATE INDEX IDX_EAP_T_REFPROCESSHISTSHEETFIELDMAPPING_CREATED_BY ON EAP_T_REFPROCESSHISTSHEETFIELDMAPPING (created_by);

