-- ============================================================
-- Indexes for: EAP_T_WFRUNTIMEFIXEDCELLS
-- ============================================================

CREATE INDEX IDX_EAP_T_WFRUNTIMEFIXEDCELLS_CREATED ON EAP_T_WFRUNTIMEFIXEDCELLS (created_on);
CREATE INDEX IDX_EAP_T_WFRUNTIMEFIXEDCELLS_MODIFIED ON EAP_T_WFRUNTIMEFIXEDCELLS (modified_on);
CREATE INDEX IDX_EAP_T_WFRUNTIMEFIXEDCELLS_CREATED_BY ON EAP_T_WFRUNTIMEFIXEDCELLS (created_by);

