-- ============================================================
-- Indexes for: EAP_U_TRANSFORMATIONCALLBACK
-- ============================================================

CREATE INDEX IDX_EAP_U_TRANSFORMATIONCALLBACK_CREATED ON EAP_U_TRANSFORMATIONCALLBACK (created_on);
CREATE INDEX IDX_EAP_U_TRANSFORMATIONCALLBACK_MODIFIED ON EAP_U_TRANSFORMATIONCALLBACK (modified_on);
CREATE INDEX IDX_EAP_U_TRANSFORMATIONCALLBACK_CREATED_BY ON EAP_U_TRANSFORMATIONCALLBACK (created_by);

