-- ============================================================
-- Indexes for: EAP_TEMP_HISTORICALUNIQUEIDENTIFIERS
-- ============================================================

CREATE INDEX IDX_EAP_TEMP_HISTORICALUNIQUEIDENTIFIERS_CREATED ON EAP_TEMP_HISTORICALUNIQUEIDENTIFIERS (created_on);
CREATE INDEX IDX_EAP_TEMP_HISTORICALUNIQUEIDENTIFIERS_MODIFIED ON EAP_TEMP_HISTORICALUNIQUEIDENTIFIERS (modified_on);
CREATE INDEX IDX_EAP_TEMP_HISTORICALUNIQUEIDENTIFIERS_CREATED_BY ON EAP_TEMP_HISTORICALUNIQUEIDENTIFIERS (created_by);

