-- ============================================================
-- Indexes for: EAP_T_OUTEMAILTEMPLATECONFIG
-- ============================================================

CREATE INDEX IDX_EAP_T_OUTEMAILTEMPLATECONFIG_CREATED ON EAP_T_OUTEMAILTEMPLATECONFIG (created_on);
CREATE INDEX IDX_EAP_T_OUTEMAILTEMPLATECONFIG_MODIFIED ON EAP_T_OUTEMAILTEMPLATECONFIG (modified_on);
CREATE INDEX IDX_EAP_T_OUTEMAILTEMPLATECONFIG_CREATED_BY ON EAP_T_OUTEMAILTEMPLATECONFIG (created_by);

