-- ============================================================
-- Indexes for: EAP_T_MANAGERELATEDACTIONSECURITY
-- ============================================================

CREATE INDEX IDX_EAP_T_MANAGERELATEDACTIONSECURITY_CREATED ON EAP_T_MANAGERELATEDACTIONSECURITY (created_on);
CREATE INDEX IDX_EAP_T_MANAGERELATEDACTIONSECURITY_MODIFIED ON EAP_T_MANAGERELATEDACTIONSECURITY (modified_on);
CREATE INDEX IDX_EAP_T_MANAGERELATEDACTIONSECURITY_CREATED_BY ON EAP_T_MANAGERELATEDACTIONSECURITY (created_by);

